apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: wildstar
  namespace: ambassador
spec:
  hostname: "*"
  selector:
    matchLabels:
      hostname: wildcard
  acmeProvider:
    authority: none
  tlsSecret:
    name: ambassador-certs
  requestPolicy:
    insecure:
      action: Redirect
      additionalPort: 8080