apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../workflows
- regcred.yaml
- gateway.yaml
- virtualservice.yaml
- destinationrule.yaml
patchesStrategicMerge:
- service.yaml
- server.yaml



