apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAGbMdG5ZBERM56roIvYLERrYIJp46tj3ZOA7hUx2mqt2IVeP38smqjvFqpPSEKHX4wogDOY/bvsvHp5CfCHhz/JrHmqU0D/UK6iKcSYXDLpuwios/BRe/q4XoU1RQpHzN10DaIxytKGv6PYmGTFzTFBMqs8zrWHUtSqUztJ/uSdAKQ5rz86LutlSzA9Qz/fV0+uFIJpc+dZ7k4gLjrM7Hp/dk28pKBIoJ7gjCWALo03j8TjPjMAvY0VnCXOIWBqNQ3alN5Qh8u/63t06poG0wThXkO6iKYUyUq/EoMiJu/xMc278gQ7NAJWTn3HiSQarAA4yEZsW6V6rq8yeOSNMwaAHvc7vP0UcN2OAUYjJWhuDxIiLBIsz2xklDUWd9WU2EzuwtCT4gt8OVa8r399zDdEzgJiddjsAzqN/5Psog+hHTSYXEp++mUzHzBqD9MjRO754esJejbd66clIfwd/HAEmPxTOUDkh2uV98jn32HAh+os1OsjZ0T6sae/7VZhNFcHzFPh02ytk3Vrwijyx182dBCsKv92CZdkKlMMnpM4sbLjkW6gYsZRJpykf8FHgMMmbl3Vtkj4ehHXLpRuHTu/RJKnQouzJaq40e9Y5Y90HbDuSp2FQvbPSBwOe/K1StUhZ7DUR6JsNEuzdLULvEQGZkVamIzjeTEjOPxotLxCJAC8kTEe9aPA6bLgHYd6Jt6irPJuKOj+EWYil3//lU8goGgUy8LJhpN35xhIg3OcMIQQbyA7LoM9/MsvbAPEzYCXQnRKNeIewLYFDO/wLCbys96+5CGgxxRIwYXoEFP5BCWC6s0b6Qq47N6e/JdqoQcGkB1H+AGHTDq5yaIL0jraT2K1J6UZRhI630X95OA00fL7dcwaOaowCuuJUW5/5BY4Yrm61v8QyZ9TBIPhQEUk3l3Q4cNCkKf1kTDHg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

