apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAwS71KTk8OMXrWy/pe1sbhCxOzta+JnNIUvb6qipDtXhCkyPyL6+0PS4lkdeTarKTk8A+OPLgtJH+tchoTMOGe2v532BuGJ/0TK7mYt8Vz6IteMRvUT+404uKVBuq5NBbwLnFh4iN6xItkhvO5h8LqRr+4F2bJ+sgrfXIvGQaLZCW1rpStWRYho1gc12xVMorURo/Gz7B3HADTIcgpR2t/CJzmfQjBDqqCQhxaME5cilNJyAV/Z4HGN25dSKHBHEeq+Hhy0Z2RPNGF//eI25RPq6kUTTsm1MpVp1IC7BBqNe2gVmItAAP0y7I1Wcvgg41pcKfTjozbSFws9+cHoK8Bn0qURmOEGked/L4piGhBgSDhYw39ci0D5X1EwJaiOXFmFg/Q2XikBJkINt4iY70Ci+G0634iVwNCqXKSIpYZS8/UQDMybras0xcKXkNsvm7oC6OVJX2OxPAKD0CpzRpMiDVVIc3EwAac0weOHDRqHobGFsWRnfXou5IxyzpSLFtlNobHvJSIbYLfe1qKZ/cngATx0/3Qi7lPmQopzJznR7vC66MYxpldDV3tqfRKrDYWVZPkhEBNGI2kYsp2C8KJ7RRVV2sQHfzs1sUepoRdOtxffwA0VSZIgvo7BRbhgr9C20JInkpzvnxmEh2zvHDYIuMCtRsPNJkWCAoE0jN5tP+try6EXwEpm7Rx1kJboN9Ix4uPDmV7Yy49E9YURKQCXMUEqjwfslKzhBOYgIx9A0sB+uiPgMP8qRnzKa1Guybttaf1yc8hj532ZXM795zrBrWZogiWg3uqYwD3XZdXAYhC1XEr9/ffL1H8J5o1ydAJfJqMwDgAS08MnKpbDK+nm/GymiXVs74M4GGh/4Z16EzHjsYqa5ZpxYMIQ2GFoacFOJ/WZxM+G+Ljp2BpLGqOaq4x2dvB35eCcB1iDQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

