---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server
spec:
  selector:
    matchLabels:
      app: argo-server
  template:
    metadata:
      labels:
        app: argo-server
    spec:
      containers:
      - args:
        - server
        env:
          - name: INSECURE
            value: "true"
            name: INSECURE_SKIP_VERIFY
            value: "true"
        image: quay.io/argoproj/argocli:latest
        name: argo-server    
