apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-teste
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cicd-cluster
  source:
    path: kustomize/overlays/staging
    repo: ssh://git@github.com/j-mascarenhas-tc/nginx-teste
    targetRevision: HEAD
    kustomize:
      images:
      - josemarbm23/nginx-teste:latest
  destination:
    server: https://kubernetes.default.svc
    namespace: cicd-cluster
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
--- 
apiVersion: v1
kind: Secret
metadata:
  name: nginx-teste-private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:j-mascarenhas-tc/nginx-teste
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEA1FKY0zGmqRF/tDrmRL8IerXJ1/KLMB0W1cOJOiHcV1I3JGZFLWno
r9DSnUSCbibBuF1mwzq4U3DrMjOQ0CClRErWbpHuPY6vFGyp1+FYQlcy0K1kwL/4Rvf/Pz
K9hzOqapmLz5w7tBSsnuMe+iFSODNJtkaD5s7le8FCqhHkBms2h3agpNZ7XAXV5gbBTeJ4
iTwVCc4LXiUrL6HtVmYQrvI9dHqxkp2SBI3V0f++l0519X5x3CuuAO5tUWidCWHSQ315a1
nEb5HKX0jq0sEaoTyCNrN9CT7c0/Ws4VaTREUMLd+2SDBlJ7Zao4OJmGtjHGv3czU+uUBv
cS7uVfadadgpg7jgTZj0u2c70whdWlYBKnTMUZ1g4NW3ZjiDSLurUoP6GumycQUuR8Uoaj
wxLHRecnOpspWM/6LkcYAJ997L6dM9uMQZM1UJPqCZMKOhGT/Zh4Ii5rbR2UldojgN0bAF
X24/WfxjwYwkwxRruLYym+DMHWSd1mztcD3q7sC7AAAFmJPHKAyTxygMAAAAB3NzaC1yc2
EAAAGBANRSmNMxpqkRf7Q65kS/CHq1ydfyizAdFtXDiToh3FdSNyRmRS1p6K/Q0p1Egm4m
wbhdZsM6uFNw6zIzkNAgpURK1m6R7j2OrxRsqdfhWEJXMtCtZMC/+Eb3/z8yvYczqmqZi8
+cO7QUrJ7jHvohUjgzSbZGg+bO5XvBQqoR5AZrNod2oKTWe1wF1eYGwU3ieIk8FQnOC14l
Ky+h7VZmEK7yPXR6sZKdkgSN1dH/vpdOdfV+cdwrrgDubVFonQlh0kN9eWtZxG+Ryl9I6t
LBGqE8gjazfQk+3NP1rOFWk0RFDC3ftkgwZSe2WqODiZhrYxxr93M1PrlAb3Eu7lX2nWnY
KYO44E2Y9LtnO9MIXVpWASp0zFGdYODVt2Y4g0i7q1KD+hrpsnEFLkfFKGo8MSx0XnJzqb
KVjP+i5HGACffey+nTPbjEGTNVCT6gmTCjoRk/2YeCIua20dlJXaI4DdGwBV9uP1n8Y8GM
JMMUa7i2MpvgzB1kndZs7XA96u7AuwAAAAMBAAEAAAGAeyEjS2bB1c42FtkJbNi0HCWMVl
Vr7o0QDwuEa1fzphghrlQ4zetba4pYeaefVC3ZrgdMbu+AsbMMUmKhGnG0JfSYgirS1JQI
aHnTzUP7oQ1chLPpd/ZcDxwGxCmyy9Nkgslk0RMzdG2A5eukrT3hpoHnv3MJTzKw1qHu/R
2+9RH733cmFjHj/CvOLcXBGF+7sypKsRLyeLhpYQgw0SgDiNEmXoRAslv6r/VpCI2dg7WW
prWbZilWkWezscBPQX+eFseItS6Yn1HE3UtMYapfhPgaw603hgJ/bXfXebS9RBl4A7N/xR
kkthVN4qZpQSUeQNxoUiHWTtpb4nSfvhk+5IzmGsfXpdYKeAUA7WyK0ffbMrCSe9mkNNjU
dRq186cNSItYf7UHJKKAwgj52LfbaDqNCZsbMxrhkDX8uvKSRVsaac+g13IZOikY5LgyUC
ba352XwFdoNb6L3aSTMpMJc/PkI+lwutU7uCFeHXqYS3cgjxFfZL4Yi1kF+vXYQvnhAAAA
wBROo9SwJdi8wI4RVPt8I7Qz7YX3pPGQcE1X+k2LXDCaskoWdiziSWSVv3nc1r3ejK5DMu
EDYm9+W0XHxsOTGTlMPmZ92UnixCJH2MlLqtHpfE1X+sPEnCM8v6N6jeKIGwi5dfOsxuXr
BmFVobimfqM0Vx1eJTuDDTlmXOsPbpwmaBVOX0O/0qxXSwjejhAiRKeCHszjx/EVmmiXlM
rZbsmKJFfmjlcWgzLUCDk/H085x1VTCLb+lzQoSA5OxWqqBQAAAMEA/3UvCxLSTi3Y0qIN
116HbyrdFchQa+fr/wbC3cHrCIEeLFH3hGOcPnJBYxzptbGH1KjDHJ/vm6ZT8Zks3+5XaD
1sxZFzNVUwGGd+ZsxZc4KFFrLsb5V+6hEiQ21GpmDge/7Ia5asCkAvX3Z+U0aX3UpBhFdf
HnDmcZxa8/tTTTPINw5zag7QhonIS0Kx/8Ra7za6pK0XI2FdXkkucDn78SawXPyMnydy2y
UfOKshG0lS1yiA7U29V0x1wTJdjSfpAAAAwQDUxfk39iGa0gS2WF3bnTH5zP7rAW9G7tKn
3ML2hnqBXjEWJ6y8YmooUBM3dCoDNBMX1vkE8c1CNpMX54pKSJR6vfl2FN94cLUJR1JH1n
3v405PhMlefmDLnIy+WwZviH659NNq0xtaG89/VrUtyD1B7BhLexy4VzfkXiZVVmPe+AT4
0g4rgCk3lteeJuDX7NHOpDWgYffbl0sKanuVsaHM8JPUKJ/GA3DsrEAVFS00xMadoDr7FQ
yzVP9ldvPoYQMAAAAdam9zZW1hci5tYXNjYXJlbmhhc0B0Yy5jb20uYnIBAgMEBQY=
-----END OPENSSH PRIVATE KEY-----
    

