apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-teste
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cicd-cluster
  source:
    path: kustomize/overlays/staging
    repoURL: https://github.com/j-mascarenhas-tc/nginx-teste
    targetRevision: HEAD
    kustomize:
      images:
      - josemarbm23/nginx-teste:latest
  destination:
    server: https://kubernetes.default.svc
    namespace: cicd-cluster
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

