apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBQL+UO4PWrrBJm5tsAYqT0z2QLhixiHRKaUCLFRs8mP4F3HcBMN32/Naplf7pVmoxNzaMYYVtblUz4MsvtrrbHxZU5rflmhLLKJLSVpY2pfcDskfMkOwKpyxGQ3wN1/FdE7b5G0Pn2Oekk6Kna29eUYeZ5ZOLHz7vY/0rDsdHDKmCqLMdx8yDjgBkhzWbOBUli4c0oETK9uJJsFdV3vPBHQocLyXgP85o6qEx2XpG51e5mYHtqqfBHyAQvRcwKQFMnRNwxTapzJUNrocjLwXm363Hv6dO8QYci7f/FQf5bQR1Po0II1ogs8VyIpU20mLKZjRCTfFj+hYiKfUr4hO9RzRc4A5AieI+z9ks8T6J+KZrlwzaXbPUGb1suwMLUjfhgQyDlsaTLDQGP8KEiOhqoCfsuW80/2fIn9IotHJAEs3QWooBT/6IhW92G0dhM1bNdLpXaXohcHIbM/c8eKJpL3f3MGVwblUUX/EalCMuSwoKEj0Op9UbwuDXWyTWZdyXNmV8n9ldK/GY9GjpPoe3lWsabh7vlekdhi4YdUhgjxVk0T+qm7vV4PCmpDZORXmvwBt1EvACJnzQ6w77nNXq2JehZ11mrTvzrKMHzVuwbeWE90Rse7P9De70uFnhIhsetl2pwlEOe9VzRmQLK4TZ3npgj5pbz7a+mNrNEv8+KUzv02Ugy2za46EPev3Bc8s0ygv13/1g2jGiQXJdYbpMI7mBIAikGZlw0pf8HUWdoHLK+Ip9eBaxF
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

