apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAkZeabEqwmjP6avzp7EtnsFJfs3HcEuk+zoxvtw33FfP2Ql0yN90kAMdVjs8gOX3H/9SP0CyIcoHwicvAm0anxp4h9ewPseBu70ds7km0fab7wllu9nPmEXGZf1CmH0t7ZS4RmaiRfvNjK/wXa8TEaaSWuIU9jBAFjv2E+R9xAdBvzAQ3UE9TDH703d60b+hrVxuNxpKrUeJGxOf0uA+ZXUeU5tf+J2tw1I0EfBXIuJOiletfAMNoe+bU5YIY1790noG32nOvC21lIVT6g0IZpVEbydWzIn1iL1HQlVcqtnNey+hyL3YTmFIO7Buy3YbwNq7yD1vgdocb3E5ToHqtEn+P4tbyQmWn2uhHDoTIMg4gZ3yKEKagM3Xrj9hxfrqGbydarx1Ae7UTJWmRW7B4AyO1/GrGHFp5n5x+Y6TSBcXNeKCxFOsiUz7kx3BpfRY0evNr2BEWIZi0lRgoXItBu/60qkjtOU52RFwxMwlHbwOeABEbB/i+NLwwmJ39wG559eDMVWzHXKDbikcv9SRdPtgNfA2inds8AEwhxMZMQFRFDJP9xO2yyZ8C970149se6ASp12vwZApqB9nBgrAnzlc4J+fxJOYJkgudMTbG6qqo+UkdONo88eqdhOU6uxNrxYQ69MMVm7DHKqsSy4lnh4jR8oTis46prAV+XBq9KcWlae1DLXmfwbomHcRTo6mTwk64QlFt7PpGuttxEXYeXcMaKizMCayHI2lhdNFUQazcjAHM6/xYA
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

