apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCkZVZN7/W7mZHsFeTqa1DATt3eA1pvCFEf/yOTRz2G1+YgST8k1Fv1UjDddmrergaIye8Usy617ZfASF7RA5bOkjwIS5oWOWlpBoQ0oD8tT5SAE4KMcD9Ew2fhlsDoaMo/z5hqX2ngKvKjEZZM0wAAnbLd9h8GMzjLv/R30Qy92biJVEWmM3tTueyytaMI+8eZj1ncQSHMiXfCnCRkVSO/DbJBaVbTi47rMExuQbXMoLYCGFpISS21uIdPsRm1twZLrca4J4zM8UJtC8Zhsz1xQqq5Mue94FU9QZpPxlxbynRSFSpaH3kKoL082FE7qOCHQATFnWpqzefwhxDmzgXTYLWNOQSfgwIHSeR3xZ3eV/H+/P0I09qqGM+SLL9wqJSCSdv5Ad/kLnCoOGWdb2bu+nxJPRE9PVUHBIPAFUaIGDa4IKtAlbTYWr0v0inipSxdu1U5/0eT0rkkP28sOXDQxxg62Yf3TN4IWXVWILxyoaMm15KgmRirTh5FtYPS2PeE30QbF/KYuS28ssCbShUvCcN5MdjfePMaMlb6pjATxPEy50mLo87qAxkNueceI34odjmIzqIaRLKKKduEtchakmz/kuPz1OfGUlG2TQzRBzG257dWnGrcQkMuITM1D3mqM8HE56mKu/1MFo3n8xMJ7T2PAd+fTJILwN/tTE90dJ2sgPtX7axjR7waYki66IKT4EK1uyntEdkauNV9CJ3PJSwVVaq7cEUzLvw0FOKeUqEmmj2ATAD1
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

