apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCqXIOFgFodfOVgBTrWMfc/ZDkrqjfVzU5vqftdriTotzlcW+N//T0RHrl7V3/hrhMt8LAw8MuzI70ikeOZfzSPXC3ogAn+wRB6CV7V69X+pClikSGTpLdgiqlxFJeJfiwwUOjJBRHS4pGMEn1UWsSnwu2lpogYH41hPlO8n1RGqhV6x2t3Q4f8/wtEDKMA/v0P/E4z1jg9pb0sCsVyXOrvmGKd99wz9nvfBjb++uDqhv5z6SeG3JGvX2Qj+NMs6Dbe41FUAtqR1zpjQOm/1Ngso1bFoNsOgdp+dPs7w9OPeERYCIbMvvVGzafYpZIIjBCVD0V+HX4OCcvxa835EkffitDG5uLGpCE1BmwhN9b5pNPv1aGXCJ80gDt2qOCPz83qZB5eiQA3K5D2Mv41rRvGuK6DHFvu/QbLR6QNPPyjMJRDJGOrdseRiZrSahB+4A1FethJwoV1j+UxKNNLC+nxQL98KG1Vkfiq/QsKoCljJm2cy/5kswEtXPSSA3E46UBj4cClavTtuseHiOjHFozW+X4UmdOD6a05BdIZlG60GvzlF/vZSeTPWfcBPv1tGPbu+WrAkzmPC4PB0jUUpcjPDoOZyJuXYQcv3/MysfUjwqsccICtwwlmKhsrvpd06QH0pTys+/XfhZXu/HC+K/QbHDGxUtGfV+//PlOB7aZXhQJEioFrwqmFraetN2LX61ZA/L+fTQxbhUZIExjTG1+hGMdV4lIHKts5YS1hJYDk5l58+FwFerzk
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

